project_id = "clinic"

[db]
port = 54322
major_version = 15

[db.seed]
enabled = true
sql_paths = ["./seed/seed.sql"]

[api]
enabled = true
port = 54321

[studio]
enabled = true
port = 54323

[auth]
enabled = true
site_url = "http://localhost:5173"
additional_redirect_urls = ["http://localhost:5173"]
