// مسارات مركزية — استخدمها دائمًا بدل كتابة strings مباشرة في الكود
export const ROUTES = {
  home: "/",
  doctors: "/doctors",
  doctorProfile: (id: string) => `/doctors/${id}`,
  nurses: "/nurses",
  nurseProfile: (id: string) => `/nurses/${id}`,
  nursesNearby: "/nurses/nearby",
  nursesUrgent: "/nurses/urgent",
  howItWorks: "/how-it-works",
  about: "/about",
  login: "/login",
  register: "/register",
  forgotPassword: "/forgot-password",
  resetPassword: "/reset-password",

  dashboard: "/dashboard",
  dashboardBookings: "/dashboard/bookings",
  dashboardBookingDetails: (id: string) => `/dashboard/bookings/${id}`,
  dashboardNotifications: "/dashboard/notifications",
  dashboardProfile: "/dashboard/profile",
  dashboardSettings: "/dashboard/settings",
  bookDoctor: (doctorId: string) => `/booking/doctor/${doctorId}`,
  bookNurse: (nurseId: string) => `/booking/nurse/${nurseId}`,

  providerDashboard: "/provider/dashboard",
  providerRequests: "/provider/requests",
  providerCalendar: "/provider/calendar",
  providerBookings: "/provider/bookings",
  providerBookingDetails: (id: string) => `/provider/bookings/${id}`,
  providerAvailability: "/provider/availability",
  providerServices: "/provider/services",
  providerReviews: "/provider/reviews",
  providerRevenue: "/provider/revenue",
  providerProfileEdit: "/provider/profile-edit",

  admin: "/admin",
  adminDoctors: "/admin/doctors",
  adminDoctorNew: "/admin/doctors/new",
  adminDoctorEdit: (id: string) => `/admin/doctors/${id}/edit`,
  adminNurses: "/admin/nurses",
  adminNurseNew: "/admin/nurses/new",
  adminNurseEdit: (id: string) => `/admin/nurses/${id}/edit`,
  adminUsers: "/admin/users",
  adminUserDetails: (id: string) => `/admin/users/${id}`,
  adminServices: "/admin/services",
  adminBookings: "/admin/bookings",
  adminBookingDetails: (id: string) => `/admin/bookings/${id}`,
  adminAnalytics: "/admin/analytics",
  adminAuditLog: "/admin/audit-log",
} as const;
